const std = @import("std");

const file_size_max = 32 * 1024 * 1024;

pub fn main(init: std.process.Init) !void {
    const gpa = init.gpa;
    const io = init.io;
    const args = try init.minimal.args.toSlice(init.arena.allocator());
    if (args.len != 3) return error.InvalidArguments;

    const input = try std.Io.Dir.cwd().readFileAlloc(
        io,
        args[1],
        gpa,
        .limited(file_size_max),
    );
    defer gpa.free(input);

    var output: std.Io.Writer.Allocating = .init(gpa);
    defer output.deinit();

    try output.writer.writeAll(
        "// Generated by Zig translate-c and sanitized by rgfw-zig.\n",
    );
    var lines = std.mem.splitScalar(u8, input, '\n');
    while (lines.next()) |line| {
        // translate-c appends every preprocessor macro after C declarations.
        // None are ABI declarations, and many SDK macros cannot exist as Zig values.
        if (std.mem.startsWith(u8, line, "pub const __VERSION__ =")) break;

        if (std.mem.indexOf(u8, line, "@compileError") != null) {
            return error.UnsupportedDeclaration;
        }

        try output.writer.writeAll(line);
        try output.writer.writeByte('\n');
    }
    try output.writer.writeAll(
        \\pub const RGFW_TRUE: RGFW_bool = 1;
        \\pub const RGFW_FALSE: RGFW_bool = 0;
        \\
    );

    try std.Io.Dir.cwd().writeFile(io, .{
        .sub_path = args[2],
        .data = output.written(),
    });
}
