const std = @import("std");
const builtin = @import("builtin");

const file_size_max = 32 * 1024 * 1024;
const macro_boundary = "pub const __VERSION__ =";

pub fn main(init: std.process.Init) !void {
    const gpa = init.gpa;
    const io = init.io;
    const args = try init.minimal.args.toSlice(init.arena.allocator());
    if (args.len != 3) return error.InvalidArguments;

    const input = try std.Io.Dir.cwd().readFileAlloc(
        io,
        args[1],
        gpa,
        .limited(file_size_max),
    );
    defer gpa.free(input);

    var output: std.Io.Writer.Allocating = .init(gpa);
    defer output.deinit();

    try sanitize(&output.writer, input);

    try std.Io.Dir.cwd().writeFile(io, .{
        .sub_path = args[2],
        .data = output.written(),
    });
}

fn sanitize(writer: *std.Io.Writer, input: []const u8) !void {
    try writer.print(
        "// Generated by Zig {s} translate-c and sanitized by rgfw-zig.\n",
        .{builtin.zig_version_string},
    );

    var found_macro_boundary = false;
    var lines = std.mem.splitScalar(u8, input, '\n');
    while (lines.next()) |line| {
        // translate-c appends every preprocessor macro after C declarations.
        // None are ABI declarations, and many SDK macros cannot exist as Zig values.
        if (std.mem.startsWith(u8, line, macro_boundary)) {
            found_macro_boundary = true;
            break;
        }

        if (std.mem.indexOf(u8, line, "@compileError") != null) {
            return error.UnsupportedDeclaration;
        }

        try writer.writeAll(line);
        try writer.writeByte('\n');
    }
    if (!found_macro_boundary) return error.MissingMacroBoundary;

    try writer.writeAll(
        \\pub const RGFW_TRUE: RGFW_bool = 1;
        \\pub const RGFW_FALSE: RGFW_bool = 0;
        \\
    );
}

test "sanitize keeps declarations and removes the translate-c macro appendix" {
    var output: std.Io.Writer.Allocating = .init(std.testing.allocator);
    defer output.deinit();

    try sanitize(&output.writer,
        \\pub const RGFW_bool = u8;
        \\pub extern fn RGFW_init() void;
        \\pub const __VERSION__ = "compiler macro";
        \\pub const unusable = @compileError("macro only");
        \\
    );

    try std.testing.expectEqualStrings(
        "// Generated by Zig " ++ builtin.zig_version_string ++
            " translate-c and sanitized by rgfw-zig.\n" ++
            "pub const RGFW_bool = u8;\n" ++
            "pub extern fn RGFW_init() void;\n" ++
            "pub const RGFW_TRUE: RGFW_bool = 1;\n" ++
            "pub const RGFW_FALSE: RGFW_bool = 0;\n",
        output.written(),
    );
}

test "sanitize rejects compile errors in ABI declarations" {
    var output: std.Io.Writer.Allocating = .init(std.testing.allocator);
    defer output.deinit();

    try std.testing.expectError(
        error.UnsupportedDeclaration,
        sanitize(&output.writer,
            \\pub const broken = @compileError("declaration");
            \\pub const __VERSION__ = "compiler macro";
            \\
        ),
    );
}

test "sanitize detects translate-c output format changes" {
    var output: std.Io.Writer.Allocating = .init(std.testing.allocator);
    defer output.deinit();

    try std.testing.expectError(
        error.MissingMacroBoundary,
        sanitize(&output.writer, "pub extern fn RGFW_init() void;\n"),
    );
}
